import requests
import json

BASE_URL = "http://127.0.0.1:8000"

def test_full_flow():
    # 1. Login
    print("Logging in...")
    auth_url = f"{BASE_URL}/api/v1/auth/login/access-token"
    # Note: I added prefix="/auth" in router.py so path is /api/v1/auth/login...
    # Wait, in router.py I did:
    # api_router = APIRouter()
    # api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
    # app/main.py includes api_router with prefix="/api/v1".
    # So URL is /api/v1/auth/login/access-token.
    
    data = {"username": "admin@example.com", "password": "password"}
    res = requests.post(auth_url, data=data)
    if res.status_code != 200:
        print(f"Login failed: {res.text}")
        return
    token = res.json()["access_token"]
    headers = {"Authorization": f"Bearer {token}"}
    print("Login successful.")

    # 2. Create Blog
    print("Creating blog...")
    blog_url = f"{BASE_URL}/api/v1/blogs" # app/api/blogs.py: @router.post("/blogs")
    # router.py included blogs with NO PREFIX? 
    # Let's check router.py content again.
    # api_router.include_router(blogs.router, tags=["blogs"])
    # blogs.py router has NO prefix in APIRouter()?
    # blogs.py: router = APIRouter(). @router.post("/blogs").
    # So path is /api/v1/blogs. Correct.
    
    blog_data = {"name": "Test Blog Agentic"}
    res = requests.post(blog_url, json=blog_data, headers=headers)
    if res.status_code != 201:
        print(f"Create blog failed: {res.text}")
        return
    blog_id = res.json()["id"]
    print(f"Blog created: {blog_id}")

    # 3. Create Version
    print("Creating version...")
    version_url = f"{BASE_URL}/api/v1/blogs/{blog_id}/versions"
    version_data = {
        "content": "This is a test blog content generated by the system to verify upload functionality. It needs to be long enough.",
        "source": "human_paste"
    }
    res = requests.post(version_url, json=version_data, headers=headers)
    if res.status_code != 201:
        print(f"Create version failed: {res.text}")
        return
    print("Version created successfully!")
    print(json.dumps(res.json(), indent=2))

if __name__ == "__main__":
    test_full_flow()
