"""initial_schema_sqlite

Revision ID: 3944edee89aa
Revises: 
Create Date: 2026-02-03 10:11:58.959337+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3944edee89aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), server_default=sa.text("'writer'"), nullable=False),
    sa.Column('is_human', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role != 'system' OR is_human = false", name='chk_system_not_human'),
    sa.CheckConstraint("role IN ('writer', 'reviewer', 'admin', 'system')", name='chk_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_is_human', 'users', ['is_human'], unique=False, sqlite_where=sa.text('is_human = 1'))
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_table('blogs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_blogs_created_at', 'blogs', ['created_at'], unique=False)
    op.create_index('idx_blogs_created_by', 'blogs', ['created_by'], unique=False)
    op.create_table('approval_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('blog_id', sa.String(length=36), nullable=False),
    sa.Column('attempted_by', sa.String(length=36), nullable=False),
    sa.Column('is_human', sa.Boolean(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('attempted_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.CheckConstraint("result IN ('success', 'forbidden', 'invalid_state', 'invalid_version')", name='chk_approval_attempts_result'),
    sa.ForeignKeyConstraint(['attempted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_approval_attempts_blog', 'approval_attempts', ['blog_id'], unique=False)
    op.create_index('idx_approval_attempts_result', 'approval_attempts', ['result'], unique=False, sqlite_where=sa.text("result != 'success'"))
    op.create_index('idx_approval_attempts_user', 'approval_attempts', ['attempted_by'], unique=False)
    op.create_table('blog_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('blog_id', sa.String(length=36), nullable=False),
    sa.Column('parent_version_id', sa.String(length=36), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=20), server_default=sa.text("'human_paste'"), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("source IN ('human_paste', 'ai_rewrite', 'human_edit')", name='chk_version_source'),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_version_id'], ['blog_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blog_id', 'version_number', name='uq_blog_version')
    )
    op.create_index('idx_blog_versions_blog_id', 'blog_versions', ['blog_id'], unique=False)
    op.create_index('idx_blog_versions_created_at', 'blog_versions', ['created_at'], unique=False)
    op.create_index('idx_blog_versions_created_by', 'blog_versions', ['created_by'], unique=False)
    op.create_index('idx_blog_versions_parent', 'blog_versions', ['parent_version_id'], unique=False)
    op.create_index('idx_blog_versions_source', 'blog_versions', ['source'], unique=False)
    op.create_table('approval_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('blog_id', sa.String(length=36), nullable=False),
    sa.Column('approved_version_id', sa.String(length=36), nullable=False),
    sa.Column('approver_id', sa.String(length=36), nullable=False),
    sa.Column('approved_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('revoked_at', sa.String(), nullable=True),
    sa.Column('revoked_by', sa.String(length=36), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_version_id'], ['blog_versions.id'], ),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_approval_states_active', 'approval_states', ['blog_id', 'approved_at'], unique=False, sqlite_where=sa.text('revoked_at IS NULL'))
    op.create_index('idx_approval_states_blog', 'approval_states', ['blog_id'], unique=False)
    op.create_table('escalations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('blog_id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending_review'"), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.String(), nullable=True),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.CheckConstraint("reason IN ('score_regression', 'policy_violation', 'ambiguity', 'low_quality')", name='chk_escalations_reason'),
    sa.CheckConstraint("status IN ('pending_review', 'resolved', 'dismissed')", name='chk_escalations_status'),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['blog_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_escalations_blog', 'escalations', ['blog_id'], unique=False)
    op.create_index('idx_escalations_pending', 'escalations', ['blog_id'], unique=False, sqlite_where=sa.text("status = 'pending_review'"))
    op.create_index('idx_escalations_status', 'escalations', ['status'], unique=False)
    op.create_table('evaluation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('blog_version_id', sa.String(length=36), nullable=False),
    sa.Column('run_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('triggered_by', sa.String(length=36), nullable=True),
    sa.Column('model_config', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'processing'"), nullable=False),
    sa.CheckConstraint("status IN ('processing', 'completed', 'partial_failure', 'failed')", name='chk_evaluation_runs_status'),
    sa.ForeignKeyConstraint(['blog_version_id'], ['blog_versions.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_eval_runs_status', 'evaluation_runs', ['status'], unique=False, sqlite_where=sa.text('completed_at IS NULL'))
    op.create_index('idx_eval_runs_version', 'evaluation_runs', ['blog_version_id'], unique=False)
    op.create_table('human_review_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('blog_version_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('performed_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("action IN ('APPROVE', 'REJECT', 'COMMENT', 'REQUEST_CHANGES', 'APPROVE_INTENT')", name='chk_human_review_actions_action'),
    sa.ForeignKeyConstraint(['blog_version_id'], ['blog_versions.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_actions_performed_at', 'human_review_actions', ['performed_at'], unique=False)
    op.create_index('idx_review_actions_reviewer', 'human_review_actions', ['reviewer_id'], unique=False)
    op.create_index('idx_review_actions_version', 'human_review_actions', ['blog_version_id'], unique=False)
    op.create_table('rewrite_cycles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_version_id', sa.String(length=36), nullable=False),
    sa.Column('target_version_id', sa.String(length=36), nullable=True),
    sa.Column('prompt_template_id', sa.String(length=36), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_version_id'], ['blog_versions.id'], ),
    sa.ForeignKeyConstraint(['target_version_id'], ['blog_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rewrite_cycles_source', 'rewrite_cycles', ['source_version_id'], unique=False)
    op.create_index('idx_rewrite_cycles_target', 'rewrite_cycles', ['target_version_id'], unique=False)
    op.create_table('aeo_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('rubric_version', sa.Text(), nullable=False),
    sa.Column('aeo_total', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('aeo_answerability', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('aeo_structure', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('aeo_specificity', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('aeo_trust', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('aeo_coverage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('aeo_freshness', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('aeo_readability', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.CheckConstraint('aeo_total >= 0 AND aeo_total <= 100', name='chk_aeo_total'),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', name='uq_aeo_run_id')
    )
    op.create_index('idx_aeo_scores_run_id', 'aeo_scores', ['run_id'], unique=False)
    op.create_table('ai_detector_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='chk_ai_detector_scores_score'),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'provider', name='uq_detector_score')
    )
    op.create_index('idx_detector_scores_run', 'ai_detector_scores', ['run_id'], unique=False)
    op.create_table('ai_likeness_rubric_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='chk_rubric_scores_score'),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', name='uq_rubric_score_run_id')
    )
    op.create_index('idx_rubric_scores_run', 'ai_likeness_rubric_scores', ['run_id'], unique=False)
    op.create_table('rewrite_suggestions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cycle_id', sa.String(length=36), nullable=False),
    sa.Column('suggested_content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'pending_user_acceptance'"), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('pending_user_acceptance', 'accepted', 'rejected')", name='chk_rewrite_suggestions_status'),
    sa.ForeignKeyConstraint(['cycle_id'], ['rewrite_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rewrite_suggestions_cycle', 'rewrite_suggestions', ['cycle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rewrite_suggestions_cycle', table_name='rewrite_suggestions')
    op.drop_table('rewrite_suggestions')
    op.drop_index('idx_rubric_scores_run', table_name='ai_likeness_rubric_scores')
    op.drop_table('ai_likeness_rubric_scores')
    op.drop_index('idx_detector_scores_run', table_name='ai_detector_scores')
    op.drop_table('ai_detector_scores')
    op.drop_index('idx_aeo_scores_run_id', table_name='aeo_scores')
    op.drop_table('aeo_scores')
    op.drop_index('idx_rewrite_cycles_target', table_name='rewrite_cycles')
    op.drop_index('idx_rewrite_cycles_source', table_name='rewrite_cycles')
    op.drop_table('rewrite_cycles')
    op.drop_index('idx_review_actions_version', table_name='human_review_actions')
    op.drop_index('idx_review_actions_reviewer', table_name='human_review_actions')
    op.drop_index('idx_review_actions_performed_at', table_name='human_review_actions')
    op.drop_table('human_review_actions')
    op.drop_index('idx_eval_runs_version', table_name='evaluation_runs')
    op.drop_index('idx_eval_runs_status', table_name='evaluation_runs', sqlite_where=sa.text('completed_at IS NULL'))
    op.drop_table('evaluation_runs')
    op.drop_index('idx_escalations_status', table_name='escalations')
    op.drop_index('idx_escalations_pending', table_name='escalations', sqlite_where=sa.text("status = 'pending_review'"))
    op.drop_index('idx_escalations_blog', table_name='escalations')
    op.drop_table('escalations')
    op.drop_index('idx_approval_states_blog', table_name='approval_states')
    op.drop_index('idx_approval_states_active', table_name='approval_states', sqlite_where=sa.text('revoked_at IS NULL'))
    op.drop_table('approval_states')
    op.drop_index('idx_blog_versions_source', table_name='blog_versions')
    op.drop_index('idx_blog_versions_parent', table_name='blog_versions')
    op.drop_index('idx_blog_versions_created_by', table_name='blog_versions')
    op.drop_index('idx_blog_versions_created_at', table_name='blog_versions')
    op.drop_index('idx_blog_versions_blog_id', table_name='blog_versions')
    op.drop_table('blog_versions')
    op.drop_index('idx_approval_attempts_user', table_name='approval_attempts')
    op.drop_index('idx_approval_attempts_result', table_name='approval_attempts', sqlite_where=sa.text("result != 'success'"))
    op.drop_index('idx_approval_attempts_blog', table_name='approval_attempts')
    op.drop_table('approval_attempts')
    op.drop_index('idx_blogs_created_by', table_name='blogs')
    op.drop_index('idx_blogs_created_at', table_name='blogs')
    op.drop_table('blogs')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_is_human', table_name='users', sqlite_where=sa.text('is_human = 1'))
    op.drop_table('users')
    # ### end Alembic commands ###
